// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s AppRoleListRolesList) Validate() error {
	switch s {
	case "true":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s AppRoleListSecretIdsList) Validate() error {
	switch s {
	case "true":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s KvV2ListList) Validate() error {
	switch s {
	case "true":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
