// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AppRoleLoginRequest) setDefaults() {
	{
		val := string("")
		s.SecretID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AppRoleReadRoleResponse) setDefaults() {
	{
		val := string("default-service")
		s.TokenType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AppRoleWriteBindSecretIdRequest) setDefaults() {
	{
		val := bool(true)
		s.BindSecretID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AppRoleWriteRoleRequest) setDefaults() {
	{
		val := bool(true)
		s.BindSecretID.SetTo(val)
	}
	{
		val := string("default-service")
		s.TokenType.SetTo(val)
	}
}
